[theme]
primaryColor = "#00d2ff"
backgroundColor = "#0a192f"
secondaryBackgroundColor = "#172a45"
textColor = "#e6f1ff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
